apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: backend-quality-studio
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: backend-quality-studio
    app.kubernetes.io/part-of: quality-dashboard
  name: backend-quality-studio
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app.kubernetes.io/instance: backend-quality-studio
status:
  loadBalancer: {}
