apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: backend-qd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: backend-qd
    app.kubernetes.io/part-of: quality-dashboard
  name: backend-qdgfht
spec:
  port:
    targetPort: 8000
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: backend-qd
    weight: 100
status: {}
